version: '2'

services:
  unicorm:
    build: .
    command: python
    depends_on:
      - mysql
    environment:
      - DB_DSN=mysql+pymysql://user:user@mysql/unicorm
    networks:
      - unicorm-net

  mysql:
    image: mysql:5.7
    networks:
      - unicorm-net
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=unicorm
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user

networks:
  unicorm-net: {}
