version: '2'

services:
  mysql:
    image: mysql:5.7
    networks:
      - sqlchemistry-net
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sqlchemistry
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - sqlchemistry-data:/var/lib/mysql

networks:
  sqlchemistry-net: {}

volumes:
  sqlchemistry-data: {}
